spring.application.name=proje

# Veritaban? Ayarlar? - Kendi yerel PostgreSQL bilgilerinizle doldurun
spring.datasource.url=jdbc:postgresql://localhost:5432/proje
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate Ayarlar? - 'create' her seferinde tablolar? s?f?rlar, 'update' verileri korur
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail Sunucu Ayarlar? - Gmail için 'smtp.gmail.com' ve '587' kullan?n
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Mail kullan?c? ad? ve uygulama ?ifrenizi Environment Variables olarak ekleyin
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true